### PR TITLE
new press page WIP, require review press page styles.

### LINKED ISSUE #80: [Press] Create new press page
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user I want to be able to see information about MARKET Protocol in the press

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: To learn more about our protocol and see what people think about us!

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No press page

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Press page!

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*: Willing to let someone take some of their creativity to create  a nice looking page.  This will be a standalone page, that has a link in the footer to it.  We will possibly add a different link to it later, but for now just a footer link is all that is needed. 

See Additional Information for some examples and the needed links we want added

### Definition of Done

- [ ] Design and implement new Press Page-  marketprotocol.io/press in line with our [style guide](https://github.com/MARKETProtocol/assets/blob/master/Branding/MARKET_Protocol-Style-Guide.pdf)
- [ ] Plan for additional media links in design
- [ ] Create needed tests
- [ ] Create link in footer to new Press Page
- [ ] Follow all branding guidelines
- [ ] Allocate time for a few revisions as we decide on any style issues that may exists.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
###
this could possibly look somthing like https://bluzelle.com/latest-news/press/ is 

Needed press links -

1. https://themerkle.com/what-is-the-market-protocol/
2. https://www.youtube.com/watch?v=iRipt7d5LPc
3. https://themerkle.com/top-four-upcoming-cryptocurrencies-sans-icos/
4. https://www.cryptoninjas.net/2018/04/23/market-protocol-to-integrate-the-dgx-gold-backed-stablecoin/
5. https://bitcoinexchangeguide.com/market-protocol-ico/

### PR DESCRIPTION
**Pull request by dreday966**
##### Description
new press page WIP, code is not completed, require review press page styles. 

##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [ ] Tests coverage hasn't decreased

##### Refers/Fixes
Fixes: #80

### CODE REVIEW

**Comment by dreday966** [comment]
@pelsasser  I added two links to the press page for review styles.
There is a problem, What image source I should use?  [bluzelle.com](https://bluzelle.com/latest-news/press/) uses image.

**Comment by dreday966** [comment]
the link of press page is '/press'

**Comment by pelsasser** [comment]
@dreday966 - thanks! sorry for the late response here, I am traveling.  On [discord](marketprotocol.io/discord) I connected you with one of our community managers who should be able to assist in this.  It not I will try and help out tomorrow.  Thanks for being patient!

**Comment by pelsasser** [comment]
@dreday966 - please LMK if @ lakikentaki got you everything you needed!

**Comment by dreday966** [comment]
added logos for different press, pls review. 
There are some logo not work with white background, so I used lightgrey.
If you want to make some style adjustments, pls tell me.

**Comment by pelsasser** [comment]
@dreday966 - just took a look at this.

A few requests 

1. https://coincrunch.io/ - this is the people that did the interview in the second item, can we use their art rather than the generic YouTube graphic?
1. The last item - https://www.futuretechpodcast.com/podcasts/phil-elsasser-cto-co-founder-market-protocol/ - has the wrong logo as well. 
1. Can we center the art vertically against the corresponding text?
image
1. For the images that don't show up on a white background can we use a charcoal (from the stylye guide) box around their logo? I think this will allow us to still use a white background. 

Thanks for your hard work on this!

**Comment by dreday966** [comment]
Hi @pelsasser, it's my reply.

1. No problem.

> 2.The last item - https://www.futuretechpodcast.com/podcasts/phil-elsasser-cto-co-founder-market-protocol/ - has the wrong logo as well.

The logo for futuretechpodcast.com is missing. I forgot to mention this.

3. No problem.

> 4.For the images that don't show up on a white background can we use a charcoal (from the stylye guide) box around their logo? I think this will allow us to still use a white background.

, I tried to use a light grey background color on the images, but it looks weird that each image have a different size.

**Comment by pelsasser** [comment]
Here is a logo for them. 
https://www.futuretechpodcast.com/wp-content/uploads/2017/01/Future-Tech-Podcast-Logo-PNG.png

4. Can we standardize the size of the charcoal box we use to mitigate this?

**Comment by dreday966** [comment]
@pelsasser 
image
looks not good with cryptoNinja, use different color with cryptoNinja?

**Comment by dreday966** [comment]
@pelsasser 4 requests handled. cryptoNinja uses white background. Have a look.

**Comment by pelsasser** [comment]
thanks @dreday966 - gonna merge this.  A few changes here and there but I can make them just as easily as asking you! Thanks for the hard work on this!

**Comment by pelsasser** [comment]
@dreday966 - appears there are some errors with the production build here - 

> 
>  ReferenceError: Failed exporting HTML for URL press (src/containers/Press): window is not defined
>   
>   - static.46c66a2b.js:1019 Press.componentWillMount
>     /home/pelsasser/website/dist/static.46c66a2b.js:1019:36
>   
>   - react-dom-server.node.development.js:2154 processChild
>     [website]/[react-dom]/cjs/react-dom-server.node.development.js:2154:16
>   
>   - react-dom-server.node.development.js:2048 resolve
>     [website]/[react-dom]/cjs/react-dom-server.node.development.js:2048:5
> 

> 
>   
>   - react-dom-server.node.development.js:2333 ReactDOMServerRenderer.render
>     [website]/[react-dom]/cjs/react-dom-server.node.development.js:2333:22
>   
>   - react-dom-server.node.development.js:2307 ReactDOMServerRenderer.read
>     [website]/[react-dom]/cjs/react-dom-server.node.development.js:2307:19
>   
>   - react-dom-server.node.development.js:2679 renderToString
>     [website]/[react-dom]/cjs/react-dom-server.node.development.js:2679:25
>   
>   - index.js:524 renderToStringAndExtract
>     [website]/[react-static]/lib/static/index.js:524:68
>   
>   - static.config.js:53 Object.renderToHtml
>     /home/pelsasser/website/static.config.js:53:18
>   
>   - index.js:561 _callee5$
>     [website]/[react-static]/lib/static/index.js:561:39
>   
>   - runtime.js:62 tryCatch
>     [website]/[regenerator-runtime]/runtime.js:62:40
>   
>

**Comment by pelsasser** [comment]
please fix and I can get bounty paid out

**Comment by dreday966** [comment]
Hi @pelsasser, I figured out how to fix this. How I do with git, just push a new commit?

**Pull request merged**
