### PR TITLE
Create captions and photo card for each article for external sharing …

### PR DESCRIPTION
**Pull request by bakaoh**
##### Description
Add need tags to blog posts that are generated by CMS

##### Checklist
- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Affected core subsystem(s)
Blog

##### Testing
Local

##### Refers/Fixes
Fixes: #203

### CODE REVIEW

**Comment by rojosnow** [comment]
@nitinrgupta Sorry, I see that @eswarasai has already assigned himself.

**Comment by eswarasai** [comment]
@bakaoh -- I've tested out the changes you've done and couldn't see them working. I think, the `static.config.js` compiles the entire static website at runtime and generates the html files. So the meta tag checks which are present are always defaulted. The best way to tackle this is to render the `meta` component via the [`renderMeta.helmet.meta`](https://github.com/MARKETProtocol/website/blob/develop/static.config.js#L179) as done here -- https://github.com/MARKETProtocol/website/blob/develop/src/App.tsx#L63

Let me know if this makes sense and also you need any help. Thanks!

**Comment by bakaoh** [comment]
@eswarasai --- i tried using `helmet` at first, it's seem working with `npm start`, but not with `npm run build`, so i have to use another solution. What are you using for production deploy?

You can test my current solution here http://whalefootprint.com/blog/post/kleros-partners-with-market-protocol-for-decentralized-derivatives-trading
screenshot from 2018-08-09 09-36-43

**Comment by eswarasai** [comment]
@bakaoh -- Yeah. Getting `helmet` to work as expected with the `react-static` build is pretty difficult. Unfortunately we're using build files deployed to AWS S3 to host static website. Did you try the suggested solution like we're using for `App.tsx` in `Blog.tsx`?

**Comment by bakaoh** [comment]
Yes, i tried it, but when i build, the static html didn't contain the meta as expected. My solution didn't replace meta when run as dev, but it did at static html

**Comment by eswarasai** [comment]
@bakaoh -- Hmm. Weird. Can you explain which solution worked for static html i.e., build? The commit of this PR doesn't work with `npm run build` but with `npm run start`, if my understanding is correct?

**Comment by bakaoh** [comment]
This pr work with npm run build but not with npm run start. Using helmet working with npm run start but not with npm run build

**Comment by eswarasai** [comment]
@bakaoh -- Ahh. I got it all wrong. Let me test out the PR with the build and update you. It's fine if it doesn't work with dev server since the target is production website :)

**Pull request merged**
