### PR TITLE
Blog Post UI

### PR DESCRIPTION
**Pull request by palevoo**
##### Description
Blog Post UI Design

##### Checklist
- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [ ] Tests coverage hasn't decreased

##### Refers/Fixes
Fixes: #141

### CODE REVIEW

**Comment by eswarasai** [comment]
@palevoo -- Is this ready for review or a WIP? And also please rebase your branch with that of `upstream:develop` and do fix the conflicts. Thanks!

**Comment by eswarasai** [comment]
@palevoo -- Just checking in again to see if there's any update here? Thanks!

**Comment by eswarasai** [comment]
@pelsasser -- Can you please take a look at this PR? One concern @palevoo has is w.r.t. displaying the recommended posts at the end of the blog post. Currently we're filtering the blog posts that have same category and displaying 3 of them that belong to the same category as that of the blog post.

My suggestion is to add the recommended blog posts to the metadata of the post markdown file and render them accordingly. This falls out of the scope of actual issue though. So if you can let us know what's recommended, @palevoo would be happy to help us with :)

**Comment by pelsasser** [comment]
@eswarasai - lets get this merged and we can scope out an issue to add better recommendations

Reviewing now

**Comment by pelsasser** [comment]
@palevoo - this looks great. Few minor things from a visual review - 

image
vs mock
image

Can we make the vertical height of this more in line with the mock?


image
Is it possible to anchor the `Subscribe` button to the bottom of the section so it is always in line with the Join our Telegram?

And the final thing is it looks like the test coverage has decreased quite a bit.  Otherwise, this looks great and lets get it merged!

**Pull request merged**
