### PR TITLE
[WIP] Integrating Netlify CMS blog

### PR DESCRIPTION
**Pull request by bradysheridan**
##### Description

I'm submitting this work in progress PR to update you with where I'm at on the blog project. To check out the CMS dashboard, boot up the website, visit `localhost:3000/admin`, and login via GitHub.

> Note: When you create a new post, you're pushing it to my fork of the website, not the origin repo itself. It won't be visible in the frontend unless you pull the update from my fork.

##### Done
- [x] Integrated Netlify CMS backend
- [x] Used code from [this example](https://github.com/nozzle/react-static/tree/master/examples/netlifycms) to pull blog .md files and serve them to `/blog` and `/blog/post-title` routes
- [x] Designed and developed blog using React, meeting all parameters defined in the initial issue

##### To Do

- [x] Finalize blog post category colors
- [x] Fix a bug where, while reading a blog post, 'Blog' is not highlighted in the header
- [x] Write test code for new React components
- [x] Write a markdown doc, highlighting key changes to shared files, explaining how the CMS works, and suggesting how blog updates might fit into the current website deployment process.
- [ ] Hand off the code!

### CODE REVIEW

**Comment by pelsasser** [comment]
@bradysheridan -

thanks!  I am requesting a code review from @eswarasai but functionality looks good to me.  We will work on the design aspects as we get more assets back from our designer.  So not too concerned with that, more testing for functionality.  I cannot login to the netlify admin because of course I don't have push access to your repo or branch, but no problems there. We can test and configure once we go through with the hand off. 

What does < 1 > nav bar on top of the categories navigate?

Thanks for the quick turnaround on all of this.

**Comment by eswarasai** [comment]
@bradysheridan -- Overall it's looking good but I'll do a thorough code review once the PR is ready to be reviewed. Thanks!

**Comment by bradysheridan** [comment]
@pelsasser The `< 1 >` is a pagination controller. It'll turn into `< 1 2 3 ... >` as more pages are added (right now the max number of posts per page is 5). I can render it conditionally if there are more than 1 page of posts, it's definitely a bit confusing to just have a nondescript `< 1 >` sitting there.

**Comment by pelsasser** [comment]
@bradysheridan - that all sounds good, maybe we only need it on the bottom of the page as well and not over the Categories section.

**Comment by bradysheridan** [comment]
@pelsasser @eswarasai Alright, should be ready for a review. I'm pretty inexperienced with tests and wrote them as best I could, so any advice on that front would be much appreciated.

**Comment by eswarasai** [comment]
@bradysheridan -- You can use `MemoryRouter` similar to this -- https://github.com/MARKETProtocol/website/blob/develop/test/containers/Partners/Partners.test.tsx#L14

Please do let me know what all assistance you'd need in order to increase the coverage. ~20% coverage decrease isn't acceptable for us to move forward to merge the PR. Hope you understand. Thanks :)

**Comment by bradysheridan** [comment]
@eswarasai Of course, totally understand! MemoryRouter looks like it'll fix most of my issues. I'm going to have to slow down with this issue a bit as I have another project with a Thursday morning deadline, but I'll try to get this finished up by Friday.

**Comment by bradysheridan** [comment]
@eswarasai Coverage is up to 88.748%, and commits are squashed. Hopefully this makes the cut!

**Comment by pelsasser** [comment]
@bradysheridan - thanks for all the work on this.  

@eswarasai - LGTM we can `squash and merge` and coverage here is sufficient.  

Designer is working on the updated art/design and will have it to use shortly and we can work through the design changes once we have them in hand.

**Comment by bradysheridan** [comment]
Thanks so much guys! Work has been submitted on Gitcoin.

**Pull request merged**
