### PR TITLE
Blog updates

### PR DESCRIPTION
**Pull request by KennethAshley**
##### Description
This PR aims to update the blog page. This includes

- recent tweets
- load categories from params
- update category selection styling

##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Affected core subsystem(s)
UI, UX, Tests

##### Screenshots (Optional) 
**Recent Tweets**

**Selecting Blog Category**

**Load Category from Params**
`http://localhost:3000/blog?category=crash-courses`
image

##### Refers/Fixes
Fixes: #161

### CODE REVIEW

**Comment by pelsasser** [comment]
@KennethAshley - looks like the build is failing 

> ERROR in templates/src/containers/Blog.65182f2f.js from UglifyJs
Invalid assignment [templates/src/containers/Blog.65182f2f.js:22445,30]
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-oneOf-1-

taking a look at the design now.

**Comment by pelsasser** [comment]
more errors when trying to deploy locally, will review once resolved. 

> Blog.tsx?2622:272 Uncaught TypeError: Cannot read property '0' of undefined
    at ProxyComponent.render (Blog.tsx?2622:272)
    at ProxyComponent.hotComponentRender (react-hot-loader.development.js?8641:622)
    at ProxyComponent.proxiedRender (react-hot-loader.development.js?8641:637)
    at finishClassComponent (react-dom.development.js?5f5d:8389)
    at updateClassComponent (react-dom.development.js?5f5d:8357)
    at beginWork (react-dom.development.js?5f5d:8982)
    at performUnitOfWork (react-dom.development.js?5f5d:11814)
    at workLoop (react-dom.development.js?5f5d:11843)
    at HTMLUnknownElement.callCallback (react-dom.development.js?5f5d:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?5f5d:138)
    at invokeGuardedCallback (react-dom.development.js?5f5d:187)
    at replayUnitOfWork (react-dom.development.js?5f5d:11318)
    at renderRoot (react-dom.development.js?5f5d:11885)
    at performWorkOnRoot (react-dom.development.js?5f5d:12449)
    at performWork (react-dom.development.js?5f5d:12370)
    at performSyncWork (react-dom.development.js?5f5d:12347)
    at requestWork (react-dom.development.js?5f5d:12247)
    at scheduleWorkImpl (react-dom.development.js?5f5d:12122)
    at scheduleWork (react-dom.development.js?5f5d:12082)
    at Object.enqueueSetState (react-dom.development.js?5f5d:6644)
    at ProxyComponent.Component.setState (react.development.js?d08b:238)
    at ProxyComponent._callee$ (Router.js?b1fd:250)
    at tryCatch (runtime.js?7fcd:62)
    at Generator.invoke [as _invoke] (runtime.js?7fcd:296)
    at Generator.prototype.(anonymous function) [as next] (webpack-internal:///../../regenerator-runtime/runtime.js:114:21)
    at step (Router.js?b1fd:55)
    at eval (Router.js?b1fd:55)

**Comment by eswarasai** [comment]
@pelsasser -- Looks like the build failing issue is on `develop` already. Weird that the Travis CI isn't failing. I'll take a look into it tomorrow and fix the issue of build failing.

**Comment by pelsasser** [comment]
@eswarasai - I just built locally on develop no prob.

**Comment by eswarasai** [comment]
@pelsasser -- Is your `develop` up-to-date? Because it's failing for me locally which I know why exactly, due to the recent Blog changes.

**Comment by eswarasai** [comment]
@KennethAshley -- Can you please avoid merging `develop` into your branch? Instead please do rebase with `upstream/develop`. Thanks!

**Comment by pelsasser** [comment]
@KennethAshley @eswarasai - visually this is all good to go by me, if you guys can work through the remaining issues together would love to get it merged.

@KennethAshley - @eswarasai  is probably a little busy this week ;) but we will try to get this all wrapped up asap.

**Comment by KennethAshley** [comment]
@pelsasser i'll continue to crank on the tests. Its an easy fix i believe.

**Comment by eswarasai** [comment]
@KennethAshley -- Cool. Let me know if you need any assistance. Thanks!

**Comment by KennethAshley** [comment]
@pelsasser looking into this now. But to get this out sooner then later if anyone would love to provide assistance on the tests i'd kindly accept it.

**Comment by pelsasser** [comment]
How is this going guys? ready to be merged?

**Comment by KennethAshley** [comment]
@pelsasser @eswarasai I believe this is ready to go. Just need sign off.

**Comment by eswarasai** [comment]
@KennethAshley -- Can you rebase your branch with `upstream:develop`? Looks like there are some merge conflicts. I'll try and get this merged tomorrow. Sorry for the delay.

**Comment by eswarasai** [comment]
@KennethAshley -- Why are the commits from `upstream:develop` are part of the PR? Are you facing any issues during rebase?

**Comment by KennethAshley** [comment]
@eswarasai not sure why that keeps happening. should be fixed now

**Comment by eswarasai** [comment]
@KennethAshley -- Thanks for taking care of it. I'll get this merged ASAP and will either create separate issues to take care of or will fix them right away if possible.

**Pull request merged**
