### PR TITLE
Convert whitepaper.pdf to html

### LINKED ISSUE #137: [Whitepaper] Create html version of white paper using react-static
### User Story

As a crypto enthusiast I want to be able to find MARKET Protocol in search engines.

### Why Is this Needed?

*Summary*: SEO improvements from content in white paper.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
white paper is only available as a .pdf

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
we should create a html version 

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*: New html based option for viewing white paper

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] Convert current white paper into a nice readable format that ends up as html on the site for better SEO
- [ ] If there is a way to automate this so when we update the white paper we can avoid having to manually update this page
- [ ] Create tests for code written

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

ref #97

### PR DESCRIPTION
**Pull request by iamonuwa**
##### Description

Convert whitepaper from pdf to html 

##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Affected core subsystem(s)

UI
##### Refers/Fixes

Fixes #137

### CODE REVIEW

**Comment by pelsasser** [comment]
@iamonuwa thanks for the WIP PR! just checked it out and looks like your making a lot of progress.

**Comment by iamonuwa** [comment]
@pelsasser thank you.

**Comment by pelsasser** [comment]
@iamonuwa - thanks! 

A few notes here. 

1. Tests seem to be failing, can you take a look at the issues there
1. "Table of Content"  --> "Table of Contents"
1. In the table of contents is it possible to remove the page numbers and have the sections linked? The page numbers don't seem to make a lot of sense since they don't exist here.
1. I can tell this was a way bigger task than I originally anticipated.  Adding some ETH to thank you for the hard work.

**Comment by iamonuwa** [comment]
@pelsasser am working on fixing everything tonight. Will push as soon as I've fixed everything. Thank you for your reviews.

**Pull request merged**
