### PR TITLE
Use Link component instead of anchor component to avoid page reload

### LINKED ISSUE #122: 'The minds behind MARKET Protocol' link should not trigger a page reload
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

As a developer, I want any internal page links on the app to trigger a page reload.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

### Current Behavior
[comment]: # (Describe what actually happened.)
Clicking on 'The minds behind MARKET Protocol' button causes a page reload.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
'The minds behind MARKET Protocol' button should not a page reload 

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Go to https://marketprotocol.io/partners/
- Click on 'The minds behind MARKET Protocol' button at the bottom

### PR DESCRIPTION
**Pull request by arun1595**
##### Description

Use `Link` component around 'The Minds behind the MARKET Protocol' team button to avoid page reload.

##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Affected core subsystem(s)

UX

##### Refers/Fixes

Fixes #122

### CODE REVIEW

**Comment by pelsasser** [comment]
@arun1595 - functionality looks good, but tests are failing, can you please look into that before we merge this?

Thanks for all the PRs!!

**Comment by pelsasser** [comment]
still failing ;(

**Comment by arun1595** [comment]
@pelsasser I'll have to update the tests, will get to it in a while.

**Comment by pelsasser** [comment]
@arun1595 - thanks

**Comment by arun1595** [comment]
@eswarasai Thanks for helping me fixing the broken tests!

@pelsasser This is ready for review.

**Pull request merged**
