### PR TITLE
[Team / Advisors] Add New Advisors To /Team Page.

### LINKED ISSUE #47: [Team / Advisors] Add new advisors to /team page.
### Why Is this Needed?
*Summary*: We have added some new advisors to the project and would like to add them to the /team page.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:  Feature

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] Edit attached photos to match https://www.marketprotocol.io/team/ advisors section
- [ ] Add to photos of linkedin profiles to /team
- [ ] Create all needed tests for code written (test for /team page are currently not in place, so you will need to create them)

### Additional Information
rob_behnke
https://www.linkedin.com/in/rbehnke/

kevin2_preview
https://www.linkedin.com/in/owocki/

## Before you `start work`
If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### PR DESCRIPTION
**Pull request by brentoneill**
##### Description

Added the two new advisors to the team page and added tests.

##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Affected core subsystem(s)

Tests, UI (/team page)

##### Testing

Added 5 new tests for the `/team` page.

##### Refers/Fixes

Fixes #47

### CODE REVIEW

**Comment by brentoneill** [comment]
@pelsasser - Not sure why that image ended up like that? After converting to SVG it seems to have gotten significantly washed out. As a .png, it does not seem to have that issue. 

Noted, re: squashing commits on future PRs

**Comment by pelsasser** [comment]
@brentoneill - let me know if you have a suggested fix for that - otherwise I can turn to one of our designers.

**Comment by bradysheridan** [comment]
@brentoneill Try converting to SVG with Sketch if you haven't already, I've never seen the wash out issue doing that but I have seen it with online converters.

**Comment by brentoneill** [comment]
@bradysheridan  - I used sketch to export as SVG. I used the same method for Kevin Owocki's portrait and it worked fine...

@pelsasser  - My only suggested fix I can think of is using the .png, but that does not match the rest of the images' format.

**Comment by brentoneill** [comment]
@nitinrgupta  - Tried messing with the color profiles, but no luck...

**Comment by brentoneill** [comment]
Went ahead and dropped in the .png of Rob Behnke and it looks much better. Hopefully this is acceptable for now so we can get this merged. 

Screenshot for reference:
screen shot 2018-05-03 at 7 41 32 am

**Pull request merged**
