### PR TITLE
[NavBar] Add dropdown under white paper to allow for selection of white paper language. 

### PR DESCRIPTION
**Pull request by brentoneill**
##### Description

This PR converts the "Whitepaper" link in the header menu to a dropdown to allow for multiple languages of the whitepaper to be linked to from the header. Right now this is needed to allow for the Chinese language whitepaper to be accessible from the header menu.

##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Affected core subsystem(s)

UI, Tests

##### Refers/Fixes

https://github.com/MARKETProtocol/website/issues/46

### CODE REVIEW

**Comment by brentoneill** [comment]
@nitinrgupta Please advise on how to handle the dropdown for Whitepapers in the mobile menu. 

Here are some screenshots for reference:

Desktop:
screen shot 2018-05-03 at 8 40 52 am


Mobile:
screen shot 2018-05-03 at 8 41 02 am

**Comment by pelsasser** [comment]
@brentoneill - I reached out to one of our other designer's (not @nitinrgupta) to ask and his feedback was  

> I think the dropdown is nice on desktop. On mobile i think having it in the same menu is ok but i dont like the box within the box. I would just make the secondary menu smalller test and slightly inset.

Would love to get @nitinrgupta take as well, but he is pretty swamped these days so may not hear from him immediately

**Comment by eswarasai** [comment]
@brentoneill -- Is it possible to update the SubMenu of WhitePaper to the one like here? -- https://ant.design/components/menu/#components-menu-demo-vertical

**Comment by nitinrgupta** [comment]
@brentoneill I agree with @pelsasser's comment. The desktop looks fine. But the menu box inside the menu box doesn't look that good. 
We could do something like what @eswarasai pointed to for the mobile resolutions. 

Here's a mock for reference. 
screen shot 2018-05-06 at 7 42 38 pm

**Comment by eswarasai** [comment]
@brentoneill -- Any update here? Let us know if you need any help in case you're stuck. Thanks!

**Comment by brentoneill** [comment]
@eswarasai  - Thank you for your patience. Just got the mobile sub menu implemented as requested. 

Here's a screenshot:
screen shot 2018-05-07 at 11 36 23 am

**Comment by eswarasai** [comment]
@brentoneill -- I see that you've committed `package-lock.json` with huge diff. Not really sure why that happened. Could you `rm -rf node_modules`, rebase your branch with `MARKETProtocol/website:develop` and push the changes without having any diff for `package-lock.json`? Please ensure that you rebase and do not merge the upstream. Thanks!

**Comment by eswarasai** [comment]
@brentoneill -- One more thing, not really sure why there are so many weird commits in your branch. Is it possible to squash them all and just have a single commit with all the changes? This helps us to keep our commit history clean and we'd really like to ensure that for all the PRs. Sorry about having to ask multiple requests :)

**Pull request merged**
