### PR TITLE
Add sitemap

### LINKED ISSUE #61: [SEO] Create sitemap and robots.txt
### Why Is this Needed?

*Summary*: Sites with a programmatically readable sitemap and hints in robots.txt have improved search rankings and better appearance/formatting in search results.

### Description

*Type*: Enhancement

### Solution

Create a sitemap for marketprotocol.io and add a sitemap attribute to the site's robots.txt 
Additionally, consider referencing content both at the main marketprotocol.io and docs.marketprotocol.io sites to aid navigability and association between the two.  If possible to also be able to integrate our [medium](https://medium.com/market-protocol) which we use for blogging. 

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] add sitemap
- [ ] build out robots.txt 
- [ ] add applicable tests

### Additional Information
More details about sitemaps can be found here https://support.google.com/webmasters/answer/183668?hl=en

## Before you `start work`
If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### PR DESCRIPTION
**Pull request by arun1595**
##### Description

Adds a sitemap.xml to help crawlers index the pages in the site.

##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Refers/Fixes

Fixes #61

### CODE REVIEW

**Comment by pelsasser** [comment]
@arun1595 - took a look at the PR -  I apologize as this certainly isn't my area of expertise, but how can we allow google to crawl the docs.marketprotocol.io domain as well?

**Comment by arun1595** [comment]
@pelsasser We've to deploy a `robots.txt` and `sitemap.xml` in the middleman app as well. 

Someone correct me if I am wrong.

/cc @pchuck

**Comment by pelsasser** [comment]
@arun1595 - I will have @pchuck looks this over and let us know if we are good to merge here.  

Any interest in helping us out with the same for docs.marketprotocol.io to get the sitemap running there as well.  Dissapointed that content on docs.marketprotocol.io doesn't help us with SEO on marketprotocol.io perhaps there is a solution to remedy that?

**Comment by arun1595** [comment]
@pelsasser 

> I will have @pchuck looks this over and let us know if we are good to merge here

Sounds good!

> Dissapointed that content on docs.marketprotocol.io doesn't help us with SEO on marketprotocol.io perhaps there is a solution to remedy that?

I am not sure, will search online to see if it is possible.

**Comment by pelsasser** [comment]
http://www.bloggingflail.com/subdomains-vs-subdirectories-seo/

I wonder if linking a subdirectory to the subdomain cheats this or something.

**Comment by pchuck** [comment]
It is possible to have the sitemap for docs.marketprotocol.io and marketprotocol.io on marketprotocol.io and avoid a "cross submission error"... 

As I understand https://www.sitemaps.org/protocol.html, we need to signal in docs.marketprotocol.io's robots.txt the fact that site's sitemap lives elsewhere, e.g.:

docs.marketprotocol.io/robots.txt:
  User-agent: *
  Allow: /
  Sitemap: http://marketprotocol.io/sitemap-docs.xml

Then in marketprotocol.io/robots.txt
  User-agent: *
  Allow: /
  Sitemap: http://marketprotocol.io/sitemap-main.xml

**Comment by arun1595** [comment]
@pchuck Right. May I know the significance of having the sitemap in the website domain?

It's still isolated from the main sitemap. Not sure if I am missing something.

**Comment by pchuck** [comment]
Right. This doesn't solve the issue that docs.marketprotocol.io links can't be placed in marketprotocol.io's sitemap. But it does allow us to store all the sitemaps on the static site host, and it creates a logical association between docs.marketprotocol.io and marketprotocol.io.

Suspect that creating that association might help search rankings. Currently, there's a lot of quality original content in the pdf's stored on docs.marketprotocol.io, yet searching on that terminology isn't yielding high ranks in in google search.

Would like to experiment with this and see the effect before taking other steps (such as relocating the content from docs.marketprotocol.io to marketprotocol.io, or converting PDF content to page content) which are more involved.

**Comment by arun1595** [comment]
@pchuck Makes sense. I'll update the PR with the sitemap for docs. 

And I'll open up a PR on the docs project to generate the `robots.txt` file. Upon a quick google search, looks like there's a gem which lets us generate robots.txt 

https://github.com/yterajima/middleman-robots

If you've got another idea, let me know.

Thanks!

**Comment by pelsasser** [comment]
thanks @arun1595 and @pchuck appreciate the coordination here

**Comment by arun1595** [comment]
@pchuck I've pushed a commit with the sitemap for the docs site.

I've also submitted a [pull request](https://github.com/MARKETProtocol/docs/pull/16) to generate robots.txt in the docs site.

Let me know if something's missing. Thanks!

/cc @pelsasser

**Comment by arun1595** [comment]
@pchuck I've added a script to automate sitemap generation. PTAL.

Thanks!

**Pull request merged**
