### PR TITLE
Fix responsiveness on jobs page

### LINKED ISSUE #131: [Jobs] implement new /jobs page
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

## User Story

As a user I want to know about all the awesome opportunities to join the MARKET Protocol Core Team in a full time capacity to help realize the decentralized future!

### Why Is this Needed?

*Summary*: Most hires will come from community members, so posting on our site is the best way to reach them 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*: Implement a /jobs page that allows users to see all open positions at MARKET Protocol and access the job descriptions.

market_jobs

Current Open Positions  -

[Head of Engineering.pdf](https://github.com/MARKETProtocol/website/files/2007278/Head.of.Engineering.pdf)

[Senior Front End Developer.pdf](https://github.com/MARKETProtocol/website/files/2007272/Senior.Front.End.Developer.pdf)

[Senior Solidity Developer.pdf](https://github.com/MARKETProtocol/website/files/2007271/Senior.Solidity.Developer.pdf)

### Definition of Done

- [ ] Implement provided design in React-Static (see below for .ai and .sketch files)
- [ ] Must be fully responsive and use existing styled components wherever possible
- [ ] PR must include tests for all code created in order to be accepted.
- [ ] header, footer and CTA can be pulled from existing pages.

### Needed files
https://github.com/MARKETProtocol/assets/blob/master/MockUps/MARKET_Protocol-Jobs.sketch
https://github.com/MARKETProtocol/assets/blob/master/MockUps/MARKET_Protocol-Jobs-Graphics.ai

### LINKED ISSUE #151: [Jobs] Issue with some widths and responsiveness
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
image

### Current Behavior
Screenshot taken at 1232

### Expected Behavior
All boxes are same size at all resolutions

### Reproduction
Looks like it happens with widths b/w 1200-1300

### PR DESCRIPTION
**Pull request by iamonuwa**
##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Refers/Fixes

Fixes #151

### CODE REVIEW

**Comment by nitinrgupta** [comment]
@iamonuwa I don't think so handling via font size is ideal. It would deviate from the design. Can we handle via container height?

**Comment by iamonuwa** [comment]
@nitinrgupta alright, I'll work on that.

**Comment by nitinrgupta** [comment]
@iamonuwa cool. You can also get away by adding some padding. Not sure though. You can try out what's the best and see.

**Comment by iamonuwa** [comment]
Working on it.

**Comment by nitinrgupta** [comment]
@iamonuwa any status on this?

**Comment by iamonuwa** [comment]
@nitinrgupta adding padding won't solve the issue. But reducing the font-size did.

**Comment by nitinrgupta** [comment]
@iamonuwa Got it. Setting a `min-height` should do instead of resizing the font-sizes. I'll just push a fix for this if you don't mind 😉

**Comment by nitinrgupta** [comment]
@iamonuwa I pushed the fix on `develop`

**Pull request closed without merging**
