### PR TITLE
Add Presale Form

### LINKED ISSUE #201: Create Pre-Sale Interest form
## Before you `start work`

Please read our contribution [guidelines](https://docs.marketprotocol.io/#contributing) and if there is a bounty involved  please also see [here](https://docs.marketprotocol.io/#gitcoin-and-bounties)

If you have ongoing work from other bounties with us where funding has not been released, please do not pick up a new issue.  We would like to involve as many contributors as possible and parallelize the work flow as much as possible.

Please make sure to comment in the issue here immediately after starting work so we know your plans for implementation and a timeline.

Please also note that in order for work to be accepted, all code must be accompanied by test cases as well.

### User Story
As a visitor to the website I want to be able to sign up to learn more about MARKET Protocol's presale.

### Why Is this Needed?
*Summary*: Intake form for people who are interested in learning more. 

### Description
*Type*: Feature

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*: Create new intake form see [here])https://www.originprotocol.com/en/presale) for an example that we can copy.

### Definition of Done
- [ ] create new /presale page with intake form
- [ ] follow all style guidelines from [here](https://github.com/MARKETProtocol/assets/blob/master/Branding/MARKET_Protocol-Style-Guide.pdf)
- [ ] Add tests for all new code created
- [ ] hook up form to our mailchimp list for data collection

### PR DESCRIPTION
**Pull request by iamonuwa**
##### Description

Add Presale form

##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Refers/Fixes

Fixes #201

### CODE REVIEW

**Comment by pelsasser** [comment]
@iamonuwa - thanks for the PR.

A few things here 

Can we move this before the `Full Name` field?
image


Can we align the text and make it more cohesive?  I know the example showed this text like this, but the background tied it together.  With ours we dont have a background so lets just align is all. 
image

When someone selects US citizenship, and also selects they are NOT accredited, can we disable the submit button and add some sort of warning.  `Sorry, this is limited to Accredited Investors`.  Also if the `You Agree that...` section is not selected can we also disable the submit button. 
image


The drop down menu that select the currency for `Desired Allocation` is very hard to read.  The dark highlight on a dark text doesn't seem to work.  Can we remedy that?

Finally, it also seems this is connect to the general mailing list and not the new list.  Did @lakikentaki get you the needed information for the new list for pre-sale?

**Comment by iamonuwa** [comment]
I'll fix that now.

I don;t really know which one is the new list for pre-sale. But @lakikentaki did send me information for the form

**Comment by iamonuwa** [comment]
@pelsasser changing the text to white, will be okay?

**Comment by pelsasser** [comment]
@iamonuwa - white text when selected?  That seems like it could work.

Mail chimp list - 
u=ef1f265a21b4aae9002084ee3
id=9b6a6fd0ec

**Comment by pelsasser** [comment]
@iamonuwa please let me know if you need anything else from us!

**Comment by iamonuwa** [comment]
@pelsasser is there any prior styling for the select tag?

**Comment by nitinrgupta** [comment]
@iamonuwa you mean the drop-down? Can you share a screenshot of the select tag here if you don't mind?

**Comment by iamonuwa** [comment]
image

**Comment by iamonuwa** [comment]
If I can override it

**Comment by nitinrgupta** [comment]
Oh gosh! It's using the default one. Please override it.

**Comment by nitinrgupta** [comment]
We're overriding styles of Menu component here:
https://github.com/MARKETProtocol/website/blob/develop/src/components/Navbar.tsx#L25

Can do similarly.

**Comment by iamonuwa** [comment]
@nitinrgupta got it!

**Comment by pelsasser** [comment]
@iamonuwa - please let me know when the others changes are made so we can get this one closed out and you paid ;)

**Comment by iamonuwa** [comment]
Cool

**Comment by iamonuwa** [comment]
@pelsasser @nitinrgupta please review

**Comment by iamonuwa** [comment]
@pelsasser please review

**Comment by eswarasai** [comment]
@iamonuwa -- Can you resolve the merge conflict and also remove `yarn.lock` from your commit? Thanks!

**Comment by pelsasser** [comment]
Thanks @iamonuwa - 

After I type and select a Country I see a loading symbol?

image

And the following in the console - 

> [HMR] Waiting for update signal from WDS...
> methods.js?ce14:419 React-Static data hot-loader websocket connected. Listening for data changes...

any ideas?

**Comment by iamonuwa** [comment]
No idea, but will look at it now

**Comment by iamonuwa** [comment]
@pelsasser the loading effect is from the validator

**Comment by eswarasai** [comment]
@iamonuwa -- Looks like the tests in `Presale` are failing. Can you please fix them? Thanks!

**Comment by eswarasai** [comment]
@iamonuwa -- Why isn't there a required field validation before submitting the form? Can you please add proper validations for all the required fields of the form?

Also, when I hover over the `Select` field, the icon is covered in the black background. Probably some CSS style that needs to be overridden.

screen shot 2018-07-31 at 10 27 12 pm

**Comment by rojosnow** [comment]
@iamonuwa, how are you doing here?

**Comment by iamonuwa** [comment]
@rojosnow @eswarasai I took ill since Friday. I pushed. Please review

**Comment by lakikentaki** [comment]
Is this now live on dev.website?

**Pull request merged**
