### PR TITLE
Dependencies cleanup

### PR DESCRIPTION
**Pull request by arun1595**
##### Description

Removes unused dependencies from the project.

##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Refers/Fixes

Fixes https://github.com/MARKETProtocol/website/issues/59

### CODE REVIEW

**Comment by eswarasai** [comment]
@arun1595 -- What's the significance of this [commit](https://github.com/MARKETProtocol/website/pull/70/commits/9bba3deb41be8f8b6bf5a96f264d355411f5e3bf)?

**Comment by arun1595** [comment]
@eswarasai The PR removes unused dependencies - `axios` and `jest-matcher-utils` from the codebase.

**Comment by arun1595** [comment]
@eswarasai Weird, that commit had a couple of semi-colon insertions. Let me remove it.

**Comment by arun1595** [comment]
@eswarasai I've removed the stray commit. Let me know if there's anything missing in my PR. 

Thanks!

**Comment by pchuck** [comment]
Looks good in that the number of prerequisite libs appears to be significantly reduced. 

Were you able to test that the site still functions comparably as the deployed production site (by running locally), or that removing *required* library actually breaks the automated tests? (I'm not sure sure that the tests that are running here are sufficient to validate the dependencies.)

**Comment by arun1595** [comment]
@pchuck 

> Were you able to test that the site still functions comparably as the deployed production site (by running locally)

I did :smile:

**Comment by eswarasai** [comment]
@arun1595 -- Can you also remove the `serve` dependency along with the `serve` npm script and update the PR? Thanks

**Comment by arun1595** [comment]
@eswarasai Done!

**Comment by arun1595** [comment]
@eswarasai Looks like the `serve` package is a dependency of `react-static` package.

I am not sure if we can remove it from `package-lock.json`. Do let me know if I am wrong.

Thanks!

**Comment by arun1595** [comment]
@eswarasai And FYI, I removed the `serve` script in the `makefile`. It was referring to `server` npm script (I assume it's a typo)

**Comment by eswarasai** [comment]
> `serve` package is a dependency of `react-static` package

Dependencies are automatically downloaded. We don't require it to be another `dependency` in the `package.json`. Could you please run the command I've requested above and commit the changes?

> I've removed the serve script in the makefile

Cool. Thanks for that. I think it was a typo and since we weren't using, never bothered I guess.

**Comment by arun1595** [comment]
>  Could you please run the command I've requested above and commit the changes?

Already done :)

**Comment by eswarasai** [comment]
@arun1595 -- Also as a small note, w're working to standardize some of our PR process, if you don't mind squashing your commits for PRs going forward that would be awesome. I'm going to merge this now and close the PR. Thanks for your contribution :)

**Comment by arun1595** [comment]
> if you don't mind squashing your commits for PRs going forward that would be awesome.

@eswarasai Sure, will keep in mind!

**Pull request merged**
